"""
Copilot SDK - Python Client for GitHub Copilot CLI

JSON-RPC based SDK for programmatic control of GitHub Copilot CLI
"""

from .client import (
    ConnectionState,
    CopilotClient,
    ExternalServerConfig,
    GetAuthStatusResponse,
    GetStatusResponse,
    ModelBilling,
    ModelCapabilities,
    ModelInfo,
    ModelPolicy,
    PingResponse,
    SessionContext,
    SessionLifecycleEvent,
    SessionLifecycleEventType,
    SessionLifecycleHandler,
    SessionListFilter,
    SessionMetadata,
    StopError,
    SubprocessConfig,
    TelemetryConfig,
)
from .generated.session_events import PermissionRequest, SessionEvent
from .session import (
    SYSTEM_PROMPT_SECTIONS,
    Attachment,
    AzureProviderOptions,
    BlobAttachment,
    CopilotSession,
    CustomAgentConfig,
    DirectoryAttachment,
    FileAttachment,
    MCPLocalServerConfig,
    MCPRemoteServerConfig,
    MCPServerConfig,
    PermissionHandler,
    PermissionRequestResult,
    ProviderConfig,
    SectionOverride,
    SectionOverrideAction,
    SectionTransformFn,
    SelectionAttachment,
    ShellExitHandler,
    ShellExitNotification,
    ShellOutputHandler,
    ShellOutputNotification,
    ShellOutputStream,
    SystemMessageAppendConfig,
    SystemMessageConfig,
    SystemMessageCustomizeConfig,
    SystemMessageReplaceConfig,
    SystemPromptSection,
    Tool,
    ToolHandler,
    ToolInvocation,
    ToolResult,
)
from .tools import define_tool

__version__ = "0.1.0"

__all__ = [
    "CopilotClient",
    "CopilotSession",
    "ConnectionState",
    "ExternalServerConfig",
    "GetAuthStatusResponse",
    "GetStatusResponse",
    "PingResponse",
    "StopError",
    "FileAttachment",
    "DirectoryAttachment",
    "SelectionAttachment",
    "BlobAttachment",
    "Attachment",
    "TelemetryConfig",
    "AzureProviderOptions",
    "ProviderConfig",
    "SessionContext",
    "SessionListFilter",
    "SessionMetadata",
    "SessionLifecycleEvent",
    "SessionLifecycleEventType",
    "SessionLifecycleHandler",
    "MCPLocalServerConfig",
    "MCPRemoteServerConfig",
    "MCPServerConfig",
    "CustomAgentConfig",
    "ModelBilling",
    "ModelCapabilities",
    "ModelInfo",
    "ModelPolicy",
    "PermissionHandler",
    "PermissionRequest",
    "PermissionRequestResult",
    "SectionOverride",
    "SectionOverrideAction",
    "SectionTransformFn",
    "SessionEvent",
    "ShellExitHandler",
    "ShellExitNotification",
    "ShellOutputHandler",
    "ShellOutputNotification",
    "ShellOutputStream",
    "SubprocessConfig",
    "SystemMessageAppendConfig",
    "SystemMessageConfig",
    "SystemMessageCustomizeConfig",
    "SystemMessageReplaceConfig",
    "SystemPromptSection",
    "SYSTEM_PROMPT_SECTIONS",
    "Tool",
    "ToolHandler",
    "ToolInvocation",
    "ToolResult",
    "define_tool",
]
