#!/usr/bin/env bash
#
# Snapshot the Copilot CLI version + per-platform release hashes for the
# rust crate's bundled-in-process build path.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUST_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${RUST_DIR}/.." && pwd)"
PACKAGE_FILE="${REPO_ROOT}/nodejs/package.json"
OUTPUT="${RUST_DIR}/cli-version-in-process.txt"

if [[ ! -f "${PACKAGE_FILE}" ]]; then
  echo "error: ${PACKAGE_FILE} not found" >&2
  exit 1
fi

VERSION="$(node -e "console.log(require('${PACKAGE_FILE}').copilotCliVersion)")"
if [[ -z "${VERSION}" ]]; then
  echo "error: could not read copilotCliVersion from ${PACKAGE_FILE}" >&2
  exit 1
fi

CHECKSUMS_URL="https://github.com/github/copilot-cli/releases/download/v${VERSION}/SHA256SUMS.txt"
SHA256SUMS="$(curl -fsSL --retry 3 --retry-delay 2 "${CHECKSUMS_URL}")"

PACKAGES=(
  "copilot-darwin-arm64"
  "copilot-darwin-x64"
  "copilot-linux-arm64"
  "copilot-linux-x64"
  "copilot-linuxmusl-arm64"
  "copilot-linuxmusl-x64"
  "copilot-win32-arm64"
  "copilot-win32-x64"
)

TEMP_OUTPUT="${OUTPUT}.tmp.$$"
trap 'rm -f "${TEMP_OUTPUT}"' EXIT
{
  echo "# Auto-generated by rust/scripts/snapshot-bundled-in-process-version.sh"
  echo "# Do not edit. Regenerated by the publish workflow on every release."
  echo "version=${VERSION}"
  for package in "${PACKAGES[@]}"; do
    platform="${package#copilot-}"
    asset="github-copilot-${VERSION}-${platform}.tgz"
    hash="$(printf '%s\n' "${SHA256SUMS}" | awk -v a="${asset}" '$2 == a { print $1 }')"
    if [[ -z "${hash}" ]]; then
      echo "error: SHA256SUMS.txt missing entry for ${asset}" >&2
      exit 1
    fi
    echo "${package}=${hash}"
  done
} > "${TEMP_OUTPUT}"
mv "${TEMP_OUTPUT}" "${OUTPUT}"
trap - EXIT

echo "Wrote ${OUTPUT} (version=${VERSION}, ${#PACKAGES[@]} hashes)"
