#!/usr/bin/env bash
#
# Snapshot the Copilot CLI version + per-platform SHA-256 hashes for the
# rust crate's bundled-CLI build.rs. Runs at SDK publish time, mirroring
# how .NET's _GenerateVersionProps BeforeTargets="Pack" target writes
# GitHub.Copilot.SDK.props before NuGet packing.
#
# Input:
#   - ../nodejs/copilot-cli.json - checked-in version and trusted hashes.
#
# Output:
#   - cli-version.txt (in the rust crate root). Gitignored.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUST_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${RUST_DIR}/.." && pwd)"
MANIFEST_FILE="${REPO_ROOT}/nodejs/copilot-cli.json"
OUTPUT="${RUST_DIR}/cli-version.txt"

if [[ ! -f "${MANIFEST_FILE}" ]]; then
  echo "error: ${MANIFEST_FILE} not found" >&2
  exit 1
fi

VERSION="$(node -e "console.log(require('${MANIFEST_FILE}').version)")"
if [[ -z "${VERSION}" ]]; then
  echo "error: could not read version from ${MANIFEST_FILE}" >&2
  exit 1
fi

ASSETS=(
  "copilot-darwin-arm64.tar.gz"
  "copilot-darwin-x64.tar.gz"
  "copilot-linux-arm64.tar.gz"
  "copilot-linux-x64.tar.gz"
  "copilot-win32-arm64.zip"
  "copilot-win32-x64.zip"
)

TEMP_OUTPUT="${OUTPUT}.tmp.$$"
trap 'rm -f "${TEMP_OUTPUT}"' EXIT
{
  echo "# Auto-generated by rust/scripts/snapshot-bundled-cli-version.sh"
  echo "# Do not edit. Regenerated by the publish workflow on every release."
  echo "version=${VERSION}"
  for asset in "${ASSETS[@]}"; do
    hash="$(node -e "console.log(require(process.argv[1]).cliHashes[process.argv[2]] || '')" "${MANIFEST_FILE}" "${asset}")"
    if [[ -z "${hash}" ]]; then
      echo "error: ${MANIFEST_FILE} missing trusted hash for ${asset}" >&2
      exit 1
    fi
    echo "${asset}=${hash}"
  done
} > "${TEMP_OUTPUT}"
mv "${TEMP_OUTPUT}" "${OUTPUT}"
trap - EXIT

echo "Wrote ${OUTPUT} (version=${VERSION}, ${#ASSETS[@]} hashes)"