#!/usr/bin/env bash
#
# Snapshot the Copilot CLI version + per-platform release hashes for the
# rust crate's bundled-in-process build path.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUST_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${RUST_DIR}/.." && pwd)"
MANIFEST_FILE="${REPO_ROOT}/nodejs/copilot-cli.json"
OUTPUT="${RUST_DIR}/cli-version-in-process.txt"

if [[ ! -f "${MANIFEST_FILE}" ]]; then
  echo "error: ${MANIFEST_FILE} not found" >&2
  exit 1
fi

VERSION="$(node -e "console.log(require('${MANIFEST_FILE}').version)")"
if [[ -z "${VERSION}" ]]; then
  echo "error: could not read version from ${MANIFEST_FILE}" >&2
  exit 1
fi

PACKAGES=(
  "copilot-darwin-arm64"
  "copilot-darwin-x64"
  "copilot-linux-arm64"
  "copilot-linux-x64"
  "copilot-linuxmusl-arm64"
  "copilot-linuxmusl-x64"
  "copilot-win32-arm64"
  "copilot-win32-x64"
)

TEMP_OUTPUT="${OUTPUT}.tmp.$$"
trap 'rm -f "${TEMP_OUTPUT}"' EXIT
{
  echo "# Auto-generated by rust/scripts/snapshot-bundled-in-process-version.sh"
  echo "# Do not edit. Regenerated by the publish workflow on every release."
  echo "version=${VERSION}"
  for package in "${PACKAGES[@]}"; do
    platform="${package#copilot-}"
    hash="$(node -e "console.log(require(process.argv[1]).runtimeHashes[process.argv[2]] || '')" "${MANIFEST_FILE}" "${platform}")"
    if [[ -z "${hash}" ]]; then
      echo "error: ${MANIFEST_FILE} missing trusted hash for ${platform}" >&2
      exit 1
    fi
    echo "${package}=${hash}"
  done
} > "${TEMP_OUTPUT}"
mv "${TEMP_OUTPUT}" "${OUTPUT}"
trap - EXIT

echo "Wrote ${OUTPUT} (version=${VERSION}, ${#PACKAGES[@]} hashes)"
