#!/usr/bin/env bash
# Copyright (c) Microsoft Corporation. All rights reserved.
#
# Snapshot the Copilot CLI version + per-platform release hashes for the
# rust crate's bundled-in-process build path.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUST_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${RUST_DIR}/.." && pwd)"
OUTPUT="${RUST_DIR}/cli-version-in-process.txt"
source "${SCRIPT_DIR}/snapshot-release.sh" "$@"

PACKAGES=(
  "copilot-darwin-arm64"
  "copilot-darwin-x64"
  "copilot-linux-arm64"
  "copilot-linux-x64"
  "copilot-linuxmusl-arm64"
  "copilot-linuxmusl-x64"
  "copilot-win32-arm64"
  "copilot-win32-x64"
)

TEMP_OUTPUT="${OUTPUT}.tmp.$$"
trap 'rm -f "${TEMP_OUTPUT}"' EXIT
{
  echo "# Auto-generated by rust/scripts/snapshot-bundled-in-process-version.sh"
  echo "# Do not edit. Regenerated by the publish workflow on every release."
  echo "version=${VERSION}"
  if [[ "${RELEASE_URL}" != "${DEFAULT_RELEASE_URL}" ]]; then
    echo "release-url=${RELEASE_URL}"
  fi
  for package in "${PACKAGES[@]}"; do
    platform="${package#copilot-}"
    asset="github-copilot-${VERSION}-${platform}.tgz"
    hash="$(snapshot_hash "${asset}")"
    echo "${package}=${hash}"
  done
} > "${TEMP_OUTPUT}"
mv "${TEMP_OUTPUT}" "${OUTPUT}"
trap - EXIT

echo "Wrote ${OUTPUT} (version=${VERSION}, ${#PACKAGES[@]} hashes)"
