#!/usr/bin/env bash
#
# Snapshot per-platform SHA-256 hashes for the Copilot CLI release matching
# `cli-version.txt` into `cli-shas.txt`. Run by the publish workflow before
# `cargo publish`, and by `github/github-app`'s `scripts/sync-copilot-sdk.sh`
# when vendoring the SDK.
#
# Committing these hashes makes the publish workflow the trust boundary:
# every later consumer build verifies the downloaded archive against a
# hash that was captured at publish time, so an attacker who later
# re-points the release tag can't silently swap in poisoned bytes.
#
# Inputs:
#   - cli-version.txt (in the rust crate root) - pinned CLI version.
#   - https://github.com/github/copilot-cli/releases/v${VERSION}/SHA256SUMS.txt
#
# Output:
#   - cli-shas.txt (in the rust crate root). Gitignored locally.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUST_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
VERSION_FILE="${RUST_DIR}/cli-version.txt"
OUTPUT="${RUST_DIR}/cli-shas.txt"

if [[ ! -f "${VERSION_FILE}" ]]; then
  echo "error: ${VERSION_FILE} not found; write it before running this script" >&2
  exit 1
fi

VERSION="$(tr -d '[:space:]' < "${VERSION_FILE}")"
if [[ -z "${VERSION}" ]]; then
  echo "error: ${VERSION_FILE} is empty" >&2
  exit 1
fi

CHECKSUMS_URL="https://github.com/github/copilot-cli/releases/download/v${VERSION}/SHA256SUMS.txt"
echo "Fetching ${CHECKSUMS_URL}"
SHA256SUMS="$(curl -fsSL --retry 3 --retry-delay 2 "${CHECKSUMS_URL}")"

ASSETS=(
  "copilot-darwin-arm64.tar.gz"
  "copilot-darwin-x64.tar.gz"
  "copilot-linux-arm64.tar.gz"
  "copilot-linux-x64.tar.gz"
  "copilot-win32-arm64.zip"
  "copilot-win32-x64.zip"
)

{
  echo "# Auto-generated by rust/scripts/write-cli-shas.sh"
  echo "# Per-platform SHA-256 hashes for Copilot CLI v${VERSION}."
  echo "# Do not edit by hand; regenerate after bumping cli-version.txt."
  for asset in "${ASSETS[@]}"; do
    hash="$(printf '%s\n' "${SHA256SUMS}" | awk -v a="${asset}" '$2 == a { print $1 }')"
    if [[ -z "${hash}" ]]; then
      echo "error: SHA256SUMS.txt missing entry for ${asset}" >&2
      exit 1
    fi
    echo "${asset}=${hash}"
  done
} > "${OUTPUT}"

echo "Wrote ${OUTPUT} (${#ASSETS[@]} hashes for v${VERSION})"
