// GENERATED by CopilotToolProcessor — do not edit (hand-written test fixture)
package com.github.copilot.rpc.fixtures;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.github.copilot.rpc.ToolDefinition;

import java.util.*;
import java.util.concurrent.CompletableFuture;

final class SimpleTools$$CopilotToolMeta {

    private static Map<String, Object> withMeta(Map<String, Object> base, String description, Object defaultValue) {
        var result = new LinkedHashMap<String, Object>(base);
        if (description != null)
            result.put("description", description);
        if (defaultValue != null)
            result.put("default", defaultValue);
        return Collections.unmodifiableMap(result);
    }

    @SuppressWarnings({"unchecked", "rawtypes"})
    static List<ToolDefinition> definitions(SimpleTools instance, ObjectMapper mapper) {
        return List.of(new ToolDefinition("greet_user", "Greets a user by name",
                Map.of("type", "object", "properties", Map.ofEntries(Map.entry("name",
                        (Map<String, Object>) (Map) withMeta(Map.of("type", "string"), "The user's name", null))),
                        "required", List.of("name")),
                invocation -> {
                    Map<String, Object> args = invocation.getArguments();
                    String name = (String) args.get("name");
                    return CompletableFuture.completedFuture(instance.greetUser(name));
                }, null, null, null),
                new ToolDefinition("add_numbers", "Adds two numbers together",
                        Map.of("type", "object", "properties",
                                Map.ofEntries(
                                        Map.entry("a",
                                                (Map<String, Object>) (Map) withMeta(Map.of("type", "integer"),
                                                        "First number", null)),
                                        Map.entry("b",
                                                (Map<String, Object>) (Map) withMeta(Map.of("type", "integer"),
                                                        "Second number", null))),
                                "required", List.of("a", "b")),
                        invocation -> {
                            Map<String, Object> args = invocation.getArguments();
                            int a = ((Number) args.get("a")).intValue();
                            int b = ((Number) args.get("b")).intValue();
                            return CompletableFuture.completedFuture(instance.addNumbers(a, b));
                        }, null, null, null));
    }
}
