/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------------------------------------------*/

/**
 * Copilot SDK - TypeScript/Node.js Client
 *
 * JSON-RPC based SDK for programmatic control of GitHub Copilot CLI
 */

export { CopilotClient } from "./client.js";
export { CopilotSession, type AssistantMessageEvent } from "./session.js";
export { CloudSession } from "./cloud/cloudSession.js";
export { CloudSessionError } from "./cloud/missionControlClient.js";
export {
    defineTool,
    approveAll,
    convertMcpCallToolResult,
    createSessionFsAdapter,
    SYSTEM_PROMPT_SECTIONS,
    MissionControlCommandType,
} from "./types.js";
export type {
    CloudAskUserResponsePayload,
    CloudConnectOptions,
    CloudElicitationResponsePayload,
    CloudModeSwitchPayload,
    CloudPermissionResponsePayload,
    CloudPlanApprovalResponsePayload,
    CloudProgressEvent,
    CloudProgressPhase,
    CloudRepository,
    CloudSessionEvent,
    CloudSessionEventHandler,
    CloudSessionEventPayload,
    CloudSessionEventType,
    CloudSessionFailureReason,
    CloudSessionMetadata,
    CloudSessionOptions,
    CloudSessionRequestedEvent,
    CommandContext,
    CommandDefinition,
    CommandHandler,
    AutoModeSwitchHandler,
    AutoModeSwitchRequest,
    AutoModeSwitchResponse,
    ConnectionState,
    CopilotClientOptions,
    CustomAgentConfig,
    ElicitationFieldValue,
    ElicitationHandler,
    ElicitationParams,
    ElicitationContext,
    ElicitationResult,
    ElicitationSchema,
    ElicitationSchemaField,
    ExitPlanModeHandler,
    ExitPlanModeRequest,
    ExitPlanModeResult,
    ForegroundSessionInfo,
    GetAuthStatusResponse,
    GetStatusResponse,
    InfiniteSessionConfig,
    InputOptions,
    MCPStdioServerConfig,
    MCPHTTPServerConfig,
    MCPServerConfig,
    DefaultAgentConfig,
    MessageOptions,
    MissionControlTask,
    MissionControlTaskSession,
    ModelBilling,
    ModelCapabilities,
    ModelCapabilitiesOverride,
    ModelInfo,
    ModelPolicy,
    PermissionHandler,
    PermissionRequest,
    PermissionRequestResult,
    ProviderConfig,
    ResumeSessionConfig,
    SectionOverride,
    SectionOverrideAction,
    SectionTransformFn,
    SessionCapabilities,
    SessionConfig,
    SessionEvent,
    SessionEventHandler,
    SessionEventPayload,
    SessionEventType,
    SessionLifecycleEvent,
    SessionLifecycleEventType,
    SessionLifecycleHandler,
    SessionContext,
    SessionListFilter,
    SessionMetadata,
    SessionUiApi,
    SessionFsConfig,
    SessionFsProvider,
    SessionFsFileInfo,
    SystemMessageAppendConfig,
    SystemMessageConfig,
    SystemMessageCustomizeConfig,
    SystemMessageReplaceConfig,
    SystemPromptSection,
    TelemetryConfig,
    TraceContext,
    TraceContextProvider,
    Tool,
    ToolHandler,
    ToolInvocation,
    ToolResultObject,
    TypedSessionEventHandler,
    TypedSessionLifecycleHandler,
    ZodSchema,
} from "./types.js";
